### ISSUE TITLE
ChatGPT plasmoid does not save login credentials

### ISSUE THREAD

**Issue by HydeFromT70s** [samirgaire10/com.samirgaire10.chatgpt-plasma6#1]
Hi,

First of all, thanks for creating a wrapper for ChatGPT that works under QT6.

Everything works flawlessly, but I noticed that plasmoid doesn't save login data and you have to provide your login credentials again after each system reboot, which is a nuisance.

Any chance you could add an option to save login data?

**Comment by samirgaire10** [comment]
yes the cookie is not saved , and i apologize for inconvenience . i tryed to add cookie support but i was unable to do that.

https://github.com/samirgaire10/com.samirgaire10.google_gemini-plasma6/issues/1

**Comment by samirgaire10** [comment]
if someone can add cookie support then pull request plz

**Comment by Segfault-Git** [comment]
I posted it like kde bug/feature here

https://bugs.kde.org/show_bug.cgi?id=487372

**Comment by samirgaire10** [comment]
Thanks 👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻 Thanks👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻

**Comment by Segfault-Git** [comment]
@samirgaire10 Take a look at the "ChatAI" plugin. It saves all the needed data. Mb you can do the same way!

**Comment by samirgaire10** [comment]
got it . thank you .

**Comment by samirgaire10** [comment]
ok Done now it will save and login credentials and other data but i havent update from kde store or widget right now .  i will do it later

**Comment by HydeFromT70s** [comment]
I tested the fixes by manually installing the widget from this repository and can confirm that now after a reset the login credentials are remembered. Please update for convenience the widget on KDE Store as well.

Thanks for the fix.

**Comment by samirgaire10** [comment]
yes ok
